version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/king-sourcing-ui
    overwrite: yes
permissions:
  - object: /
    pattern: '**'
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
